import { DeleteOutlined, FileTextOutlined, PlusOutlined, ReloadOutlined } from "@ant-design/icons";
import { Button, Card, Col, Descriptions, Drawer, Empty, Form, Input, List, Popconfirm, Row, Segmented, Statistic, Tag } from "antd";
import { useEffect, useState } from "react";
import { createTemplate, deleteHistory, deleteTemplate, getAdminOverview, getHistory, listHistory, listTemplates, listUsers } from "../lib/api";
import type { AdminOverview, HistoryDetail, HistoryItem, ResearchTemplate, User } from "../types";

type View="history"|"templates"|"admin";
export function WorkspaceDrawer({open,view,user,onClose,onLoad,onApply}:{open:boolean;view:View;user:User;onClose:()=>void;onLoad:(detail:HistoryDetail)=>void;onApply:(prompt:string)=>void}){
 const [history,setHistory]=useState<HistoryItem[]>([]),[templates,setTemplates]=useState<ResearchTemplate[]>([]),[overview,setOverview]=useState<AdminOverview|null>(null),[users,setUsers]=useState<User[]>([]),[busy,setBusy]=useState(false);const [form]=Form.useForm();
 async function refresh(){setBusy(true);try{if(view==="history")setHistory((await listHistory()).items);if(view==="templates")setTemplates((await listTemplates()).items);if(view==="admin"){setOverview(await getAdminOverview());setUsers((await listUsers()).items);}}finally{setBusy(false);}}
 useEffect(()=>{if(open)void refresh();},[open,view]);
 async function load(id:string){onLoad(await getHistory(id));onClose();}
 async function add(values:{title:string;description:string;prompt:string;category:string}){await createTemplate(values);form.resetFields();await refresh();}
 return <Drawer className="workspace-drawer" width={view==="admin"?760:560} open={open} onClose={onClose} title={view==="history"?"历史研究任务":view==="templates"?"研究模板库":"管理中心"} extra={<Button icon={<ReloadOutlined/>} loading={busy} onClick={()=>void refresh()}/>}>{view==="history"?<List dataSource={history} locale={{emptyText:<Empty description="还没有持久化任务"/>}} renderItem={item=><List.Item actions={[<Button type="link" onClick={()=>void load(item.thread_id)}>打开</Button>,<Popconfirm title="删除这条研究记录？" onConfirm={async()=>{await deleteHistory(item.thread_id);await refresh();}}><Button danger type="text" icon={<DeleteOutlined/>}/></Popconfirm>]}><List.Item.Meta avatar={<FileTextOutlined/>} title={item.query} description={<><Tag color={item.status==="completed"?"green":item.status==="failed"?"red":"blue"}>{item.status}</Tag><span>{new Date(item.updated_at).toLocaleString("zh-CN")}</span><span> · {item.citation_count||0} 个来源</span></>}/></List.Item>}/>:null}
 {view==="templates"?<><div className="template-grid">{templates.map(item=><Card key={item.id} title={item.title} extra={!item.is_public?<Popconfirm title="删除模板？" onConfirm={async()=>{await deleteTemplate(item.id);await refresh();}}><Button danger type="text" icon={<DeleteOutlined/>}/></Popconfirm>:<Tag>{item.category}</Tag>}><p>{item.description}</p><Button onClick={()=>{onApply(item.prompt);onClose();}}>使用模板</Button></Card>)}</div><Card className="template-create" title="新建私人模板"><Form form={form} layout="vertical" onFinish={add}><Form.Item name="title" label="名称" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="category" label="分类" initialValue="自定义"><Input/></Form.Item><Form.Item name="description" label="说明"><Input/></Form.Item><Form.Item name="prompt" label="提示词" rules={[{required:true,min:5}]}><Input.TextArea rows={5}/></Form.Item><Button htmlType="submit" icon={<PlusOutlined/>} type="primary">保存模板</Button></Form></Card></>:null}
 {view==="admin"&&user.role==="admin"?<>{overview?<Row gutter={12}><Col span={6}><Statistic title="用户" value={overview.users}/></Col><Col span={6}><Statistic title="任务" value={overview.tasks}/></Col><Col span={6}><Statistic title="已完成" value={overview.completed_tasks}/></Col><Col span={6}><Statistic title="引用" value={overview.citations}/></Col></Row>:null}<Card title="用户与权限" className="admin-users"><List dataSource={users} renderItem={item=><List.Item><List.Item.Meta title={`${item.display_name} · ${item.email}`} description={`${item.role} · ${item.task_count||0} 个任务`}/><Tag color={item.role==="admin"?"volcano":"blue"}>{item.role}</Tag></List.Item>}/></Card></>:null}</Drawer>;
}
