import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { cancelTask, getAuthToken, getPublicConfig, listSessionFiles, startTask, uploadSessionFiles } from "../lib/api";
import { WS_BASE_URL } from "../lib/config";
import { createThreadId, getStoredThreadId, storeThreadId } from "../lib/thread";
import type { Citation, ConnectionState, HistoryDetail, MonitorMessage, OutputFile, PublicConfig, SocketMessage, UploadedItem } from "../types";

const MAX_EVENTS=120;
const extractString=(data:Record<string,unknown>,key:string)=>typeof data[key]==="string"?data[key] as string:null;
export function useDeepAgentSession(){
 const socketRef=useRef<WebSocket|null>(null), reconnectRef=useRef<number | undefined>(undefined), heartbeatRef=useRef<number | undefined>(undefined);
 const uploadedNames=useRef(new Set<string>());
 const [threadId,setThreadId]=useState(getStoredThreadId),[publicConfig,setPublicConfig]=useState<PublicConfig|null>(null);
 const [connectionState,setConnectionState]=useState<ConnectionState>("connecting"),[events,setEvents]=useState<MonitorMessage[]>([]),[files,setFiles]=useState<OutputFile[]>([]),[citations,setCitations]=useState<Citation[]>([]);
 const [sessionPath,setSessionPath]=useState(""),[result,setResult]=useState(""),[lastError,setLastError]=useState(""),[lastPongAt,setLastPongAt]=useState("");
 const [isRunning,setIsRunning]=useState(false),[isCancelling,setIsCancelling]=useState(false),[isUploading,setIsUploading]=useState(false),[uploadedItems,setUploadedItems]=useState<UploadedItem[]>([]);
 useEffect(()=>{getPublicConfig().then(setPublicConfig).catch(e=>setLastError(e instanceof Error?e.message:"无法读取后端配置"));},[]);
 const clearTimers=useCallback(()=>{if(reconnectRef.current)clearTimeout(reconnectRef.current);if(heartbeatRef.current)clearInterval(heartbeatRef.current);},[]);
 const resetSession=useCallback(()=>{const id=createThreadId();storeThreadId(id);setThreadId(id);setEvents([]);setFiles([]);setCitations([]);setSessionPath("");setResult("");setLastError("");setUploadedItems([]);uploadedNames.current.clear();setIsRunning(false);setIsCancelling(false);},[]);
 const loadSession=useCallback((detail:HistoryDetail)=>{storeThreadId(detail.thread_id);setThreadId(detail.thread_id);setEvents(detail.events||[]);setFiles(detail.files||[]);setCitations(detail.citations||[]);setResult(detail.result||detail.error||"");setSessionPath(detail.files?.length?"history":"");setIsRunning(detail.status==="running");setIsCancelling(false);setUploadedItems([]);uploadedNames.current.clear();},[]);
 const refreshFiles=useCallback(async()=>{if(!sessionPath)return;const response=await listSessionFiles(threadId);setFiles(response.files||[]);},[sessionPath,threadId]);
 useEffect(()=>{let disposed=false;function connect(){clearTimers();socketRef.current?.close();setConnectionState("connecting");const token=getAuthToken();if(!token){setConnectionState("closed");return;}const socket=new WebSocket(`${WS_BASE_URL}/ws/${encodeURIComponent(threadId)}?token=${encodeURIComponent(token)}`);socketRef.current=socket;socket.onopen=()=>{if(disposed)return;setConnectionState("connected");setLastError("");heartbeatRef.current=window.setInterval(()=>socket.readyState===WebSocket.OPEN&&socket.send("ping"),25000);};socket.onmessage=e=>{try{const payload=JSON.parse(e.data) as SocketMessage;if(payload.type==="pong"){setLastPongAt(new Date().toISOString());return;}setEvents(previous=>[...previous,payload].slice(-MAX_EVENTS));if(payload.event==="session_created"){const path=extractString(payload.data,"path");if(path)setSessionPath(path);}if(payload.event==="sources_found"){const sources=payload.data.sources;if(Array.isArray(sources))setCitations(sources.map((s,index)=>({id:index,title:String((s as Record<string,unknown>).title||"来源"),url:String((s as Record<string,unknown>).url||""),domain:"",snippet:String((s as Record<string,unknown>).snippet||""),created_at:payload.timestamp})));}if(payload.event==="task_result"){setResult(extractString(payload.data,"result")||payload.message);setIsRunning(false);setIsCancelling(false);}if(payload.event==="task_cancelled"||payload.event==="error"){if(payload.event==="error")setLastError(payload.message);else setResult(p=>p||payload.message);setIsRunning(false);setIsCancelling(false);}}catch{setLastError("WebSocket 消息解析失败");}};socket.onerror=()=>!disposed&&setLastError("实时通道连接异常");socket.onclose=()=>{clearTimers();if(disposed){setConnectionState("closed");return;}setConnectionState("reconnecting");reconnectRef.current=window.setTimeout(connect,2000);};}connect();return()=>{disposed=true;clearTimers();socketRef.current?.close();};},[clearTimers,threadId]);
 useEffect(()=>{if(!sessionPath)return;void refreshFiles();const timer=setInterval(()=>void refreshFiles(),isRunning?2500:6000);return()=>clearInterval(timer);},[isRunning,refreshFiles,sessionPath]);
 const submitTask=useCallback(async(query:string)=>{const clean=query.trim();if(!clean)throw new Error("请输入研搜任务");setIsRunning(true);setEvents([]);setFiles([]);setCitations([]);setResult("");setLastError("");try{return await startTask(clean,threadId);}catch(e){setIsRunning(false);throw e;}},[threadId]);
 const cancelCurrentTask=useCallback(async()=>{setIsCancelling(true);try{const r=await cancelTask(threadId);if(r.status==="cancelled"){setIsRunning(false);setIsCancelling(false);}return r;}finally{setIsCancelling(false);}},[threadId]);
 const uploadFiles=useCallback(async(items:UploadedItem[])=>{const next=items.filter(i=>!uploadedNames.current.has(i.name));if(!next.length)return{status:"uploaded",files:[...uploadedNames.current]};setIsUploading(true);try{const response=await uploadSessionFiles(next.map(i=>i.raw),threadId);setUploadedItems(previous=>[...previous,...next]);next.forEach(i=>uploadedNames.current.add(i.name));return response;}finally{setIsUploading(false);}},[threadId]);
 const stats=useMemo(()=>({toolEvents:events.filter(e=>e.event==="tool_start").length,assistantEvents:events.filter(e=>e.event==="assistant_call").length,errorEvents:events.filter(e=>e.event==="error").length,fileCount:files.length}),[events,files]);
 return{connectionState,events,files,citations,isCancelling,isRunning,isUploading,lastError,lastPongAt,refreshFiles,resetSession,loadSession,publicConfig,result,sessionPath,stats,cancelCurrentTask,submitTask,threadId,uploadFiles,uploadedItems};
}
