import { ApiOutlined, AppstoreOutlined, BranchesOutlined, CheckCircleOutlined, CloseCircleOutlined, CloudServerOutlined, DatabaseOutlined, FileSearchOutlined, HistoryOutlined, LogoutOutlined, PlusOutlined, SettingOutlined, ToolOutlined, UserOutlined } from "@ant-design/icons";
import { Alert, App as AntApp, Button, Spin } from "antd";
import { useEffect, useRef, useState } from "react";
import { AuthGate } from "./components/AuthGate";
import { ChatComposer } from "./components/ChatComposer";
import { ConversationThread } from "./components/ConversationThread";
import type { ChatTurn } from "./components/ConversationThread";
import { WorkspaceDrawer } from "./components/WorkspaceDrawer";
import { useDeepAgentSession } from "./hooks/useDeepAgentSession";
import { APP_NAME, APP_TAGLINE } from "./lib/config";
import { clearAuthToken, getAuthToken, getMe, getPublicConfig } from "./lib/api";
import type { ConnectionState, HistoryDetail, IntegrationState, PublicConfig, UploadedItem, User } from "./types";

type DrawerView="history"|"templates"|"admin";
const connectionLabel=(state:ConnectionState)=>({connecting:"连接中",connected:"在线",reconnecting:"重连中",closed:"离线"}[state]);
function createTurn(content:string):ChatTurn{return{id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),content,events:[],files:[],citations:[],isRunning:true,result:"",timestamp:new Date().toISOString()};}
function Capability({label,state}:{label:string;state?:IntegrationState}){const ready=Boolean(state?.ready);return <li className={ready?"capability capability--ready":"capability"}><span className="capability-dot"/><span>{label}</span><strong>{ready?"READY":"SETUP"}</strong></li>;}

function ResearchWorkspace({user,onLogout}:{user:User;onLogout:()=>void}){
 const {message}=AntApp.useApp();const [query,setQuery]=useState(""),[stagedItems,setStagedItems]=useState<UploadedItem[]>([]),[turns,setTurns]=useState<ChatTurn[]>([]),[drawer,setDrawer]=useState<DrawerView|null>(null);const streamRef=useRef<HTMLElement|null>(null);const session=useDeepAgentSession();
 useEffect(()=>{setTurns(previous=>{if(!previous.length)return previous;const latest=previous[previous.length-1];return[...previous.slice(0,-1),{...latest,events:session.events,files:session.files,citations:session.citations,isRunning:session.isRunning,result:session.result}];});},[session.events,session.files,session.citations,session.isRunning,session.result]);
 useEffect(()=>{const node=streamRef.current;if(node)requestAnimationFrame(()=>node.scrollTo({top:node.scrollHeight,behavior:"smooth"}));},[turns]);
 async function handleSubmit(){const clean=query.trim();if(!clean){message.warning("请输入研究任务");return;}const turn=createTurn(clean);setTurns(previous=>[...previous,turn]);setQuery("");try{await session.submitTask(clean);message.success("研究任务已进入执行队列");}catch(e){setTurns(previous=>previous.map(item=>item.id===turn.id?{...item,isRunning:false,result:e instanceof Error?e.message:"任务启动失败"}:item));message.error(e instanceof Error?e.message:"任务启动失败");}}
 async function handleCancel(){try{const response=await session.cancelCurrentTask();message.info(response.status==="cancelling"?"正在等待当前调用结束":"任务已取消");}catch(e){message.error(e instanceof Error?e.message:"取消任务失败");}}
 async function handleUpload(items:UploadedItem[]){try{const response=await session.uploadFiles(items);setStagedItems([]);message.success(`已接收 ${response.files.length} 个附件`);}catch(e){message.error(e instanceof Error?e.message:"上传失败");}}
 function newSession(){session.resetSession();setTurns([]);setQuery("");setStagedItems([]);}
 function loadHistory(detail:HistoryDetail){session.loadSession(detail);setTurns([{id:detail.id,content:detail.query,events:detail.events||[],files:detail.files||[],citations:detail.citations||[],isRunning:detail.status==="running",result:detail.result||detail.error||"",timestamp:detail.created_at}]);}
 const integrations=session.publicConfig?.integrations,online=session.connectionState==="connected";
 return <div className="app-frame"><aside className="command-rail"><div className="brand-lockup"><div className="brand-mark">N</div><div><span className="eyebrow">INTELLIGENCE OS</span><h1>{APP_NAME}</h1><p>{APP_TAGLINE}</p></div></div><Button className="new-research-button" icon={<PlusOutlined/>} onClick={newSession}>新建研究任务</Button>
 <section className="rail-section"><div className="rail-heading"><span>研究空间</span><em>V2</em></div><div className="rail-nav"><button onClick={()=>setDrawer("history")}><HistoryOutlined/>历史任务</button><button onClick={()=>setDrawer("templates")}><AppstoreOutlined/>研究模板</button>{user.role==="admin"?<button onClick={()=>setDrawer("admin")}><SettingOutlined/>管理中心</button>:null}</div></section>
 <section className="rail-section"><div className="rail-heading"><span>当前会话</span><em>LIVE</em></div><div className="session-ticket"><span>CASE ID</span><strong title={session.threadId}>{session.threadId.slice(0,8).toUpperCase()}</strong><small>{session.publicConfig?.environment||"development"}</small></div></section>
 <section className="rail-section"><div className="rail-heading"><span>能力矩阵</span><em>04</em></div><ul className="capability-list"><Capability label="语言模型" state={session.publicConfig?{ready:session.publicConfig.model.ready}:undefined}/><Capability label="结构化数据库" state={integrations?.database}/><Capability label="公开网络检索" state={integrations?.web_search}/><Capability label="私有知识库" state={integrations?.knowledge_base}/></ul></section>
 <section className="rail-section rail-agents"><div className="rail-heading"><span>专家路由</span><em>03</em></div><div><CloudServerOutlined/><span>Open Web</span><small>公开情报</small></div><div><DatabaseOutlined/><span>Data Analyst</span><small>{integrations?.database.driver||"sqlite"}</small></div><div><FileSearchOutlined/><span>Knowledge</span><small>RAGFlow</small></div></section>
 <div className="rail-account"><UserOutlined/><div><strong>{user.display_name}</strong><small>{user.role} · {user.email}</small></div><Button type="text" icon={<LogoutOutlined/>} onClick={onLogout}/></div><div className="rail-footer"><span className={online?"status-led status-led--online":"status-led"}/><div><strong>{connectionLabel(session.connectionState)}</strong><small>Realtime channel</small></div><ApiOutlined/></div></aside>
 <main className="research-desk"><header className="desk-header"><div><span className="eyebrow">RESEARCH DESK / ACTIVE BRIEF</span><h2>把问题变成可追溯的研究结论</h2></div><div className={session.isRunning?"run-badge run-badge--active":"run-badge"}>{session.isRunning?<BranchesOutlined/>:<CheckCircleOutlined/>}<span>{session.isRunning?"执行中":"工作台就绪"}</span></div></header>
 <section className="metric-band"><div><span>工具调用</span><strong>{session.stats.toolEvents}</strong><ToolOutlined/></div><div><span>专家调度</span><strong>{session.stats.assistantEvents}</strong><BranchesOutlined/></div><div><span>研究产物</span><strong>{session.stats.fileCount}</strong><FileSearchOutlined/></div><div className={session.stats.errorEvents?"metric-alert":""}><span>异常事件</span><strong>{session.stats.errorEvents}</strong>{session.stats.errorEvents?<CloseCircleOutlined/>:<CheckCircleOutlined/>}</div></section>
 {session.lastError?<Alert className="workspace-alert" message={session.lastError} showIcon type="error"/>:null}<section className="research-stream" ref={streamRef}><ConversationThread onUseExample={setQuery} threadId={session.threadId} turns={turns}/></section><ChatComposer isCancelling={session.isCancelling} isRunning={session.isRunning} isUploading={session.isUploading} onCancel={handleCancel} onNewSession={newSession} onQueryChange={setQuery} onStagedItemsChange={setStagedItems} onSubmit={handleSubmit} onUpload={handleUpload} query={query} stagedItems={stagedItems} uploadedItems={session.uploadedItems}/></main>
 <WorkspaceDrawer open={drawer!==null} view={drawer||"history"} user={user} onClose={()=>setDrawer(null)} onLoad={loadHistory} onApply={setQuery}/></div>;
}

export default function App(){const [user,setUser]=useState<User|null>(null),[config,setConfig]=useState<PublicConfig|null>(null),[loading,setLoading]=useState(true);useEffect(()=>{Promise.all([getPublicConfig().then(setConfig).catch(()=>null),getAuthToken()?getMe().then(setUser).catch(()=>{clearAuthToken();setUser(null);}):Promise.resolve()]).finally(()=>setLoading(false));},[]);if(loading)return <div className="boot-screen"><Spin size="large"/><span>正在启动智研中枢…</span></div>;if(!user)return <AuthGate allowRegistration={config?.allow_registration!==false} onAuthenticated={setUser}/>;return <ResearchWorkspace user={user} onLogout={()=>{clearAuthToken();setUser(null);}}/>;}
